Future add connect jenkins
alexei-kruk-idf/flutter_laba pull request #4
Opened 2022-03-18 09:18 UTC by alexei-kruk-idf

2022-03-27 15:03 UTC, sergei-kabak-idf commented on packages/presentation/lib/screens/main_screen/main_screen.dart
> +              text: 'Card ES',
Maybe it's better to move the text to constants

2022-03-27 15:03 UTC, sergei-kabak-idf commented on packages/presentation/lib/screens/main_screen/main_screen.dart
> +              text: 'Card MX',
Maybe it's better to move the text to constants

2022-03-28 11:14 UTC, alexei-kruk-idf commented on packages/presentation/lib/screens/main_screen/main_screen.dart
> +              text: 'Card ES',
I want move constants when I'll be do localization

2022-03-28 11:15 UTC, alexei-kruk-idf commented on packages/presentation/lib/screens/main_screen/main_screen.dart
> +              text: 'Card MX',
I want move constants when I'll be do localization

2022-03-28 11:17 UTC, alexei-kruk-idf commented on packages/data/lib/repository/main_repository_impl.dart
> +        .then((value) => Mapper.jsonToMainRespone(value.data));
fixed

2022-03-28 11:31 UTC, yuliya-klescheva-idf approved these changes

2022-03-28 11:31 UTC, yuliya-klescheva-idf commented on packages/domain/lib/model/main_response.dart
> +}
Там приходит 4 поля: _class, name, color, url, если ты их не пишешь, потому что не будешь использовать, то наверное ок

2022-03-28 11:36 UTC, alexei-kruk-idf commented on packages/data/lib/helper/api_helper.dart
> +  static String login = 'flutter_lab_test';
Да в данной ветке, у меня данные были статикой, но потом я сделал их уже из формы, но это будет уже в другом пр

2022-03-28 11:36 UTC, alexei-kruk-idf commented on packages/domain/lib/model/main_response.dart
> +}
Все верно, на текущий момент, я не использую остальные поля

2022-03-28 11:38 UTC, yuliya-klescheva-idf commented on packages/data/lib/helper/api_helper.dart
> +  static String login = 'flutter_lab_test';
Супер)

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf requested changes

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/dio/dio_builder.dart
> +  );
?

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/mapper/data_mapper.dart
> +abstract class Mapper {
abstract class Mapper<Input, Output> {
Output map(Input params);
}

class JsonToMainResponseMapper implements Mapper<dynamic, List<MainResponse>>

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/main_repository_impl.dart
> +        .then((value) => Mapper.jsonToMainResponse(value.data));
remove static, pass mapper as u pass ApiService

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/model/main_response.dart
> +}
color is a status. so u can rename field into status and make it as enum with 2 fields - success and failure. while mapping, if response == 'blue' -> success, 'red' -> failure

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/main_bloc/main_bloc.dart
> +        PresentationMapper.mainResponseToCardWidget(listResponse);
static -> di

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/main_bloc/main_bloc.dart
> +    final listResponse = await _mainUseCaseImpl.call().then((value) => value);
why do u need then?

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/main_screen/main_screen.dart
> +            )
for the future - tabs will be dynamic (for some users there would be 1 tab, for some - 10 (for example)). so think over dynamic logic

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/main_screen/main_screen.dart
> +        });
seems prettier if it will be changed to StackPlatformStreamContent. it has this logic under the hood

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on pubspec.lock
>        url: "https://pub.dartlang.org"
ignore

2022-03-28 12:52 UTC, sergei-mikhailovskii-idf commented on pubspec.yaml
>      path: packages/internal
what is internal?

2022-03-28 14:14 UTC, alexei-kruk-idf commented on packages/data/lib/dio/dio_builder.dart
> +  );
я пытался сделать обработку 403 ошибки, но не смог ее отловить, поэтому на время закомментил код

2022-03-28 14:22 UTC, alexei-kruk-idf commented on packages/data/lib/mapper/data_mapper.dart
> +abstract class Mapper {
Исправил

2022-03-28 14:22 UTC, alexei-kruk-idf commented on packages/data/lib/repository/main_repository_impl.dart
> +        .then((value) => Mapper.jsonToMainResponse(value.data));
Исправил

2022-03-28 15:01 UTC, alexei-kruk-idf commented on packages/presentation/lib/bloc/main_bloc/main_bloc.dart
> +        PresentationMapper.mainResponseToCardWidget(listResponse);
Исправил

2022-03-28 16:35 UTC, alexei-kruk-idf commented on packages/presentation/lib/screens/main_screen/main_screen.dart
> +        });
Я попробую переписать на данный виджет, после добавления локализации

2022-03-28 16:39 UTC, alexei-kruk-idf commented on pubspec.lock
>        url: "https://pub.dartlang.org"
исправил

2022-03-28 16:41 UTC, alexei-kruk-idf commented on pubspec.yaml
>      path: packages/internal
В интернал хранилась сама аппа, но в следующих пр не будет данного пакета.

2022-03-28 16:46 UTC, alexei-kruk-idf commented on packages/presentation/lib/screens/main_screen/main_screen.dart
> +            )
Сделаю после локализации, ибо в последней ветке много чего поменялось в юзкейсах, поэтому потом допишу

2022-03-28 16:48 UTC, merged