Feature cards by tab v2
alexei-kruk-idf/flutter_laba pull request #8
Opened 2022-04-07 15:56 UTC by alexei-kruk-idf

2022-04-12 12:18 UTC, sergei-kabak-idf approved these changes

2022-04-12 12:18 UTC, alexei-kruk-idf commented on packages/domain/lib/model/init_main_model.dart
> +  List<TabResponse> listTabResponse;
Исправил

2022-04-12 12:18 UTC, alexei-kruk-idf commented on packages/data/lib/service/api_service.dart
> +  final Dio _dioWithOutBaseUrl;
Исправил

2022-04-13 06:08 UTC, yuliya-klescheva-idf approved these changes

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf requested changes

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/helper/api_helper.dart
> +  static String getPathView = 'https://jenkins-mobile.moneyman.ru/view/';
why did u write the whole url here instead of /view/ ?

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/main_repository_impl.dart
> +                await _secureStorage.read(key: 'password'),
u should take data from local storage via a local storage repository. keep a reference for the repository in the other repository - not the best idea (u'll have localStorageRepository in MainRepository). so, u have 2 options - pass creds from usecase (good variant, but all use cases will have the same part of code, where u get the data from local storage) or create separate interceptor, which will add the header for all API calls (the best variant)

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/main_repository_impl.dart
> +      final primaryView = _jsonToPrimaryView.map(value.data);
(optional) _jsonToTabResponseMapper.map(value.data) -> _jsonToTabResponseMapper(value.data)

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/main_repository_impl.dart
> +          path: '/view/' + view + ApiHelper.getMainInfo,
move path forming to api helper

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repository/main_repository_impl.dart
> +            ),
-//-

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/use_case_impl/init_main_tabs_use_case_impl.dart
> +  }
(optional) Future<InitMainModel> call() async {
      return await repository.initMainBloc();
    } -> Future<InitMainModel> call() => repository.initMainBloc();

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/use_case_impl/splash_use_case_impl.dart
> +  final FlutterSecureStorage secureStorage;
create separate local storage repository

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/login_bloc/login_bloc.dart
> +        await _saveLoginPasswordUseCaseImpl(loginPasswordModel);
it's better to encapsulate these 2 actions in one usecase. pass 2 repositories into signinusecase and after awaiting response from the server, save or not data to local storage

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/main_bloc/list_bloc.dart
> +        _screenData.listResponse = await _mainUseCaseImpl(_name) ?? [];
maybe add items by addAll instead of resetting reference?

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/main_bloc/list_bloc.dart
> +class _MainListBloc<T> extends BaseBlocImpl<T> implements MainListBloc<T> {
why do u have T here?

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/di/presentation_injector.dart
> +import 'package:data/mapper/json_to_primary_view.dart';
formatting - wrong imports order

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/main_screen/main_screen_list_card.dart
> +          final mainData = blocData.data!;
! -> ?

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/registration_screen/registration_screen.dart
>  class RegistrationScreenWidget extends StatelessWidget {
?

2022-04-13 09:32 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screen/splash_screen/splash_screen.dart
> +      const Duration(seconds: 3),
move delay to usecase

2022-04-13 10:10 UTC, alexei-kruk-idf commented on packages/data/lib/helper/api_helper.dart
> +  static String getPathView = 'https://jenkins-mobile.moneyman.ru/view/';
Исправил

2022-04-13 16:12 UTC, alexei-kruk-idf commented on packages/data/lib/repository/main_repository_impl.dart
> +                await _secureStorage.read(key: 'password'),
Исправил

2022-04-13 16:31 UTC, alexei-kruk-idf commented on packages/data/lib/repository/main_repository_impl.dart
> +            ),
Исправил

2022-04-13 16:44 UTC, alexei-kruk-idf commented on packages/domain/lib/use_case_impl/init_main_tabs_use_case_impl.dart
> +  }
Исправил

2022-04-13 16:44 UTC, alexei-kruk-idf commented on packages/domain/lib/use_case_impl/splash_use_case_impl.dart
> +  final FlutterSecureStorage secureStorage;
Исправил

2022-04-13 17:37 UTC, alexei-kruk-idf commented on packages/presentation/lib/bloc/login_bloc/login_bloc.dart
> +        await _saveLoginPasswordUseCaseImpl(loginPasswordModel);
Исправил

2022-04-13 17:46 UTC, alexei-kruk-idf commented on packages/presentation/lib/bloc/main_bloc/list_bloc.dart
> +        _screenData.listResponse = await _mainUseCaseImpl(_name) ?? [];
Исправил

2022-04-13 17:48 UTC, alexei-kruk-idf commented on packages/presentation/lib/screen/registration_screen/registration_screen.dart
>  class RegistrationScreenWidget extends StatelessWidget {
Оставил для себя туду чтобы не забыть, когда время будет)

2022-04-13 17:49 UTC, alexei-kruk-idf commented on packages/presentation/lib/screen/splash_screen/splash_screen.dart
> +      const Duration(seconds: 3),
исправил

2022-04-13 18:07 UTC, alexei-kruk-idf commented on packages/presentation/lib/di/presentation_injector.dart
> +import 'package:data/mapper/json_to_primary_view.dart';
Исправил

2022-04-15 16:34 UTC, merged